apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bid-product-identity-management
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: bid-product-identity-management
        image: bid-product-identity-management:kubernetes-learn
        imagePullPolicy: Never