apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bid-product
  labels:
    tier: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: bid-product
        image: bid-product:kubernetes-learn
        imagePullPolicy: Never